# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160926_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
