# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160926_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
